# Generated by Django 4.0.5 on 2022-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='reply',
            name='contents',
            field=models.TextField(),
        ),
    ]
