# Generated by Django 4.0.5 on 2022-06-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0003_reply_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='writer',
        ),
    ]
