# Generated by Django 4.0.5 on 2022-06-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_writer_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
